### ISSUE TITLE
New daily imports BitSnoop

### ISSUE THREAD

**Issue by duramato** [bitcannon-org/bitcannon-web#25]
Bitsnoop as a daily import source
http://bitsnoop.com/info/api.html

**Comment by aidanharris** [comment]
I've started work on this [here](https://github.com/aidanharris/bitcannon-web/tree/bitsnoop-provider) but the daily dumps leak memory and fail with `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory`. This is presumably because the daily dumps are so large (107MB compressed, 346MB uncompressed). I need to figure out why this is and fix it.

**Comment by OmgImAlexis** [comment]
@aidanharris if you loop over it as I was with the other provider you shouldn't get any memory issues since it only loads a single line into memory at once.

**Comment by aidanharris** [comment]
@OmgImAlexis It's pretty much exactly the same as what you were doing for KAT ([see](https://github.com/aidanharris/bitcannon-web/blob/bitsnoop-provider/background/providers/bitsnoop.js#L61-L76)). It get's data, iterates over it with lines.forEach, adds the torrent and then goes away. Am I doing something wrong / stupid? I'll dig out some profiling tools and try to see what's going on…

**Comment by OmgImAlexis** [comment]
Come to think of it I may have removed the pauses in the read stream. The pause it where it should clear the last from memory.

**Comment by OmgImAlexis** [comment]
Okay, that should be wrapped in an anonymous function like this and use the pause function of the read stream.
````
(function(){
})()
````

**Comment by aidanharris** [comment]
Closing this as [Bitsnoop](https://bitsnoop.com/) has shutdown.
