### ISSUE TITLE
Is BitCannon dead?

### ISSUE THREAD

**Issue by 2twisty** [bitcannon-org/bitcannon-web#32]
Nothing here for over 6 months -- KAT is gone, and after installing using defaults (ubuntu amd64) I see nothing in the web UI.

Please advise.

**Comment by OmgImAlexis** [comment]
Not going to lie nothing really happened because I was working on this before I left Australia to go to England, ended up homeless for a few months and I've only just gotten back into things.

@aidanharris has added a LOT over the last few months I'll be reviewing their changes and merging in as much as possible. Keep an eye out for changes over the next week or so. 👍

**Comment by OmgImAlexis** [comment]
Ref: https://github.com/bitcannon-org/bitcannon-web/pull/34
